import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Dondon Herrera | Software Engineer",
  description: "Welcome to my portfolio.",
  icons: {
    icon: [{ url: "/me_icon.ico", type: "image/x-icon" }],
    shortcut: "/me_icon.ico",
  },
  keywords: [
    "dondon-herrera",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Dondon Herrera",
    url: "https://github.com/Dondon-Herrera",
  },
} as const;
